import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Providers } from "@/providers/ThemeProvider";
import { Toaster } from "sonner";
import localFont from "next/font/local";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

const clashRoyale = localFont({
    src: [
        {
            path: "./fonts/clash-regular.woff2",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-clash-royale",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body
                className={`${manrope.variable} ${clashRoyale.variable} antialiased flex min-h-full flex-col`}
            >
                <Providers>
                    <Header />
                    <main className="flex flex-col grow pb-10 bg-base-200">
                        {children}
                    </main>
                    <Footer />
                    <Toaster
                        toastOptions={{
                            style: {
                                background: "var(--color-base-100)",
                                color: "var(--color-base-content)",
                            },
                        }}
                    />
                </Providers>
            </body>
        </html>
    );
}
